version: '3.8'

services:
  peso-wise-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=peso_wise_db
      - DB_USERNAME=peso_wise_user
      - DB_PASSWORD=peso_wise_password
      - JWT_SECRET=mySecretKey123456789012345678901234567890SecretForProduction
      - ENCRYPTION_SECRET=myEncryptionSecret12345678901234567890SecretForProduction
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
    depends_on:
      - mysql
    networks:
      - peso-wise-network
    volumes:
      - ./logs:/app/logs

  mysql:
    image: 'mysql:8.0'
    environment:
      - MYSQL_DATABASE=peso_wise_db
      - MYSQL_USER=peso_wise_user
      - MYSQL_PASSWORD=peso_wise_password
      - MYSQL_ROOT_PASSWORD=root_password_very_secret
    ports:
      - '3306:3306'
    networks:
      - peso-wise-network
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"
    networks:
      - peso-wise-network
    depends_on:
      - mysql

networks:
  peso-wise-network:
    driver: bridge

volumes:
  mysql_data:
