spring:
  application:
    name: peso-wise
  
  profiles:
    active: dev
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    
  mail:
    host: smtp.gmail.com
    port: 587
    username: ejdomingo.dev@gmail.com
    password: yglqeltpdtkqggpb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  security:
    require-ssl: false

logging:
  level:
    com.enlinka.peso_wise: DEBUG
    org.springframework.security: DEBUG
    org.flywaydb: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/peso-wise.log

app:
  jwt:
    secret: 3a91c34db160d538151a5655e16f45f2
    expiration: 15552000 # 6 months in seconds
  
  encryption:
    secret: 7ebe3b7f23e441ec5e68cff0f4ee92bb
    
  cors:
    allowed-origins: 
      - http://localhost:3000
      - http://localhost:8080
    allowed-methods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
    allowed-headers: "*"
    allow-credentials: true
